#这里不要删，有问题了可以大家一起讨论
#qq群：786310882
#项目地址: https://gitee.com/shr25/shr25-qq-robot
#创建插件wiki: https://gitee.com/shr25/shr25-qq-robot/wikis/%E6%8F%92%E4%BB%B6/%E9%80%9A%E8%BF%87%20maven%20%20archetype%20%E5%88%9B%E5%BB%BA
#项目单独配置
project:
  qq-robot:
    name: 猫猫~
    qq: 507572773
    password: 200006168235xk
    #协议 ANDROID_PHONE,  ANDROID_PAD, ANDROID_WATCH, IPAD, MACOS; 默认 ANDROID_PHONE
    protocol: ANDROID_WATCH
    #是否扫码登录，只支持MACOS、ANDROID_WATCH协议，局域网扫码
    login-by-qr: true
    #机器人工作空间
    workspace: cache
    #是否开启日志
    log-out: true
    #简化命令 true进入推荐命令模式  false 全部命令模式
    simplify-command: true
    #管理员qq列表
    root-manage-qq:
      - 1823977035
