#这里不要删，有问题了可以大家一起讨论
#qq群：786310882
#项目地址: https://gitee.com/shr25/shr25-qq-robot
#创建插件wiki: https://gitee.com/shr25/shr25-qq-robot/wikis/%E6%8F%92%E4%BB%B6/%E9%80%9A%E8%BF%87%20maven%20%20archetype%20%E5%88%9B%E5%BB%BA
#项目单独配置
project:
  qq-robot:
    qq: 机器人QQ号
    password: 机器人密码
    #机器人工作空间
    workspace: cache
    #是否开启日志
    log-out: true
    #简化命令 true进入推荐命令模式  false 全部命令模式
    simplify-command: true
    #管理员qq列表
    root-manage-qq:
      - 管理员QQ号

logging:
  level:
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.shr25: debug

#dev环境
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/shrzhr.db

#pagehelper分页插件
pagehelper:
  helperDialect: sqlite
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
