#这里不要删，有问题了可以大家一起讨论
#qq群：786310882
#项目地址: https://gitee.com/shr25/shr25-qq-robot
#demo项目地址: https://gitee.com/shr25/shr25-qq-robot-demo-plugin
#项目单独配置
project:
  qq-robot:
    qq: 机器人QQ号
    password: 机器人密码
    #机器人工作空间
    workspace: cache
    #是否开启日志
    log-out: true
    #简化命令 true进入推荐命令模式  false 全部命令模式
    simplify-command: true
    #管理员qq列表
    root-manage-qq:
      - 管理员QQ号

logging:
  level:
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.shr25: debug
#dev环境  mysql7.0
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #druid连接池配置
    druid:
      #主库数据源
      master:
        url: jdbc:mysql://localhost:3306/shrzhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      #备数据源 #关闭
      slave:
        enabled: false
        url: jdbc:mysql://localhost:3306/shrzhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        #配置初始化连接数大小
      initial-size: 10
      # 最大连接数
      maxActive: 50
      #最小连接数
      minIdle: 10
      #获取连接等待超时时间
      maxWait: 5000
      poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnection-size: 20
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 20000
      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000  # 配置一个连接在池中最大生存的时间，单位是毫秒
      #StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        urlPattern: /druid/*
        #可以增加访问账号密码【去掉注释就可以】
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true